version: "3.9"

services:
  database:
    container_name: database
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - my_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=khurshid-2827
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb
    healthcheck:
      test: pg_isready -U postgres -h localhost;
      interval: 2s
      timeout: 1s
      retries: 3
  node_app:
    container_name: node_app
    ports:
      - 3000:3000

    build:
      context: .
      dockerfile: Dockerfile
    # command : bash -c "npx prisma db push --force-reset &&   node app.js"
    command: bash -c "npx prisma migrate deploy  &&  node app.js"
    env_file:
      - .env
    depends_on:
      database :
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 5s
      timeout: 2s
      retries: 5
    
    
volumes:
  my_postgres_data : 
